<?php require 'site/header.phtml'; ?>

<title>Website - Quality Cloud-Based Software - Main</title>

<div class=siteBlurb id=siteBlurbOne>
<p>Great software for a great idea, now!</p>
<p align=center>Don't leave your good thing in someone else's hands!</p>
</div>

<div class=siteBlurb id=siteBlurbTwo>
<p>Enter this Webapp, the perfect cloud-based management tool for your business needs.</p>
Count on
<ul>
 <li>Cloud accessibility (anytime, anywhere, from any device)</li>
 <li>Secure, SOX compliant data storage and consistent backup</li>
 <li>A low, predictably flat rate (some things are good boring)</li>
</ul>
</div>

<?php require 'site/footer.phtml'; ?>
